"""
Budget & Finance Models
Personal budget tracking with bi-weekly pay periods, statement import, and auto-categorization
"""

from datetime import datetime
from enum import Enum
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, Date, Text, ForeignKey
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.orm import relationship

from .database import Base


class AccountType(str, Enum):
    CHECKING = "checking"
    SAVINGS = "savings"
    CREDIT = "credit"
    CASH = "cash"


class CategoryType(str, Enum):
    VARIABLE = "variable"
    FIXED = "fixed"
    INCOME = "income"
    TRANSFER = "transfer"


class TransactionType(str, Enum):
    DEBIT = "debit"
    CREDIT = "credit"
    TRANSFER = "transfer"


class TransactionSource(str, Enum):
    MANUAL = "manual"
    CHASE_IMPORT = "chase_import"
    NAVY_FED_IMPORT = "navy_fed_import"
    APP_EXPENSE = "app_expense"
    SYSTEM = "system"  # Auto-generated by scheduler (budget distributions)


class IncomeFrequency(str, Enum):
    WEEKLY = "weekly"
    BIWEEKLY = "biweekly"
    SEMIMONTHLY = "semimonthly"
    MONTHLY = "monthly"


class MatchType(str, Enum):
    CONTAINS = "contains"
    STARTS_WITH = "starts_with"
    REGEX = "regex"


class BudgetAccount(Base):
    """Bank/financial accounts for budget tracking"""
    __tablename__ = "budget_accounts"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    account_type = Column(SQLEnum(AccountType), nullable=False, default=AccountType.CHECKING)
    institution = Column(String(100), nullable=True)
    last_four = Column(String(4), nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    sort_order = Column(Integer, default=0, nullable=False)
    initial_balance = Column(Float, nullable=True, default=0.0)  # Starting balance to seed calculation
    balance_as_of = Column(String(10), nullable=True)  # Date when initial_balance was set (YYYY-MM-DD)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    transactions = relationship("BudgetTransaction", back_populates="account")
    income_sources = relationship("BudgetIncome", back_populates="account")
    categories = relationship("BudgetCategory", back_populates="account", foreign_keys="BudgetCategory.account_id")
    buckets = relationship("AccountBucket", back_populates="account", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<BudgetAccount {self.name}>"


class AccountBucket(Base):
    """Virtual buckets/pots within an account for tracking separate funds"""
    __tablename__ = "account_buckets"

    id = Column(Integer, primary_key=True, index=True)
    account_id = Column(Integer, ForeignKey("budget_accounts.id", ondelete="CASCADE"), nullable=False)
    name = Column(String(100), nullable=False)
    balance = Column(Float, default=0.0, nullable=False)
    sort_order = Column(Integer, default=0, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    account = relationship("BudgetAccount", back_populates="buckets")

    def __repr__(self):
        return f"<AccountBucket {self.name}: ${self.balance}>"


class BudgetCategory(Base):
    """User-defined spending/income categories"""
    __tablename__ = "budget_categories"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    category_type = Column(SQLEnum(CategoryType), nullable=False, default=CategoryType.VARIABLE)
    budget_amount = Column(Float, default=0.0)  # Per pay period budget
    monthly_budget = Column(Float, nullable=True)  # For bills that are monthly
    color = Column(String(20), default="#6B7280")
    icon = Column(String(50), nullable=True)
    is_active = Column(Boolean, default=True, nullable=False)
    show_on_dashboard = Column(Boolean, default=False, nullable=False)
    bill_day = Column(Integer, nullable=True)  # Day of month bill is due (1-31), null for variable/transfer
    owner = Column(String(20), nullable=True)  # null=shared/main, 'dane', 'kelly' for personal bills
    billing_months = Column(String(50), nullable=True)  # Comma-separated months (1-12) when bill is due, null=every month
    account_id = Column(Integer, ForeignKey('budget_accounts.id'), nullable=True)  # Which account this bill is paid from
    destination_account_id = Column(Integer, ForeignKey('budget_accounts.id'), nullable=True)  # For TRANSFER categories: which spending account receives the money
    start_date = Column(String(10), nullable=True)  # YYYY-MM format, when bill begins
    end_date = Column(String(10), nullable=True)  # YYYY-MM format, when payment plan ends
    starting_balance = Column(Float, nullable=True, default=None)  # Initial rollover balance for TRANSFER categories (seeded from external tracking)
    sort_order = Column(Integer, default=0, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    transactions = relationship("BudgetTransaction", back_populates="category")
    rules = relationship("BudgetCategoryRule", back_populates="category")
    account = relationship("BudgetAccount", back_populates="categories", foreign_keys=[account_id])
    destination_account = relationship("BudgetAccount", foreign_keys=[destination_account_id])

    def __repr__(self):
        return f"<BudgetCategory {self.name}>"


class BudgetTransaction(Base):
    """Individual financial transactions"""
    __tablename__ = "budget_transactions"

    id = Column(Integer, primary_key=True, index=True)
    account_id = Column(Integer, ForeignKey("budget_accounts.id"), nullable=False)
    category_id = Column(Integer, ForeignKey("budget_categories.id"), nullable=True)
    transaction_date = Column(Date, nullable=False)
    description = Column(String(500), nullable=False)
    original_description = Column(String(500), nullable=True)
    amount = Column(Float, nullable=False)  # Negative = expense, positive = income
    transaction_type = Column(SQLEnum(TransactionType), nullable=False, default=TransactionType.DEBIT)
    is_pending = Column(Boolean, default=False, nullable=False)
    source = Column(SQLEnum(TransactionSource), nullable=False, default=TransactionSource.MANUAL)
    source_reference_id = Column(String(100), nullable=True)
    import_hash = Column(String(64), unique=True, nullable=True)  # SHA256 for dedup
    notes = Column(Text, nullable=True)
    period_key = Column(String(10), nullable=True)  # e.g. "2026-02-1" (year-month-half)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    account = relationship("BudgetAccount", back_populates="transactions")
    category = relationship("BudgetCategory", back_populates="transactions")

    def __repr__(self):
        return f"<BudgetTransaction {self.description} ${self.amount}>"


class BudgetCategoryRule(Base):
    """Auto-categorization rules for transactions"""
    __tablename__ = "budget_category_rules"

    id = Column(Integer, primary_key=True, index=True)
    pattern = Column(String(200), nullable=False)
    match_type = Column(SQLEnum(MatchType), nullable=False, default=MatchType.CONTAINS)
    category_id = Column(Integer, ForeignKey("budget_categories.id"), nullable=False)
    priority = Column(Integer, default=0, nullable=False)  # Higher wins
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    category = relationship("BudgetCategory", back_populates="rules")

    def __repr__(self):
        return f"<BudgetCategoryRule '{self.pattern}' -> {self.category_id}>"


class BudgetIncome(Base):
    """Recurring income definitions"""
    __tablename__ = "budget_income"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    amount = Column(Float, nullable=False)
    frequency = Column(SQLEnum(IncomeFrequency), nullable=False, default=IncomeFrequency.MONTHLY)
    pay_day = Column(Integer, nullable=False)  # Day of month for monthly/semimonthly, day of week (0=Mon..6=Sun) for weekly/biweekly
    account_id = Column(Integer, ForeignKey("budget_accounts.id"), nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    account = relationship("BudgetAccount", back_populates="income_sources")

    def __repr__(self):
        return f"<BudgetIncome {self.name} ${self.amount}>"


class BudgetPeriodSnapshot(Base):
    """End-of-period summaries for trend tracking (persists after transaction cleanup)"""
    __tablename__ = "budget_period_snapshots"

    id = Column(Integer, primary_key=True, index=True)
    period_key = Column(String(10), nullable=False, unique=True)  # e.g. "2026-02-1"
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    total_income = Column(Float, default=0.0)
    total_expenses = Column(Float, default=0.0)
    total_bills = Column(Float, default=0.0)
    category_spending = Column(Text, nullable=True)  # JSON: {category_name: amount_spent}
    person_balances = Column(Text, nullable=True)  # JSON: {dane: balance, kelly: balance}
    rollover_balance = Column(Float, default=0.0)
    created_at = Column(DateTime, default=datetime.utcnow)
