"""
Weather Data Models
"""

from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, Text, Enum
from datetime import datetime
import enum

from .database import Base


class AlertSeverity(enum.Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class WeatherReading(Base):
    """Store weather readings from Ambient Weather station"""
    __tablename__ = "weather_readings"

    id = Column(Integer, primary_key=True, index=True)

    # Timestamp
    reading_time = Column(DateTime, nullable=False, index=True)
    received_at = Column(DateTime, default=datetime.utcnow)

    # Temperature
    temp_outdoor = Column(Float)  # °F
    temp_indoor = Column(Float)
    feels_like = Column(Float)
    dew_point = Column(Float)

    # Humidity
    humidity_outdoor = Column(Integer)  # %
    humidity_indoor = Column(Integer)

    # Wind
    wind_speed = Column(Float)  # mph
    wind_gust = Column(Float)
    wind_direction = Column(Integer)  # degrees
    wind_direction_avg = Column(Integer)

    # Pressure
    pressure_relative = Column(Float)  # inHg
    pressure_absolute = Column(Float)

    # Rain
    rain_hourly = Column(Float)  # inches
    rain_daily = Column(Float)
    rain_weekly = Column(Float)
    rain_monthly = Column(Float)
    rain_total = Column(Float)
    rain_rate = Column(Float)  # in/hr

    # Solar/UV
    solar_radiation = Column(Float)  # W/m²
    uv_index = Column(Integer)

    # Battery status
    battery_outdoor = Column(Integer)  # 0 or 1

    # Raw data storage
    raw_data = Column(Text)  # JSON of full API response

    # Soil moisture sensors (from AWN soil sensors) - added via ALTER TABLE
    soil_moisture_1 = Column(Integer)  # % moisture
    soil_moisture_2 = Column(Integer)
    soil_moisture_3 = Column(Integer)
    soil_moisture_4 = Column(Integer)
    soil_temp_1 = Column(Float)  # °F
    soil_temp_2 = Column(Float)

    def __repr__(self):
        return f"<WeatherReading {self.reading_time} - {self.temp_outdoor}°F>"


class WeatherAlert(Base):
    """Weather alerts generated by the system"""
    __tablename__ = "weather_alerts"

    id = Column(Integer, primary_key=True, index=True)

    alert_type = Column(String(50), nullable=False)
    # Types: frost_warning, freeze_warning, heat_warning, wind_warning,
    #        heavy_rain, storm_approaching

    severity = Column(Enum(AlertSeverity), default=AlertSeverity.WARNING)
    title = Column(String(200), nullable=False)
    message = Column(Text)

    # What triggered it
    trigger_value = Column(Float)
    threshold_value = Column(Float)

    # Affected items
    affected_plants = Column(Text)  # JSON list of plant IDs
    affected_animals = Column(Text)  # JSON list of animal IDs
    recommended_actions = Column(Text)

    # Status
    is_active = Column(Boolean, default=True)
    is_acknowledged = Column(Boolean, default=False)
    acknowledged_at = Column(DateTime)

    # Notifications
    email_sent = Column(Boolean, default=False)
    email_sent_at = Column(DateTime)

    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime)

    def __repr__(self):
        return f"<WeatherAlert {self.alert_type}: {self.title}>"


class WeatherForecast(Base):
    """Store weather forecast data (if available from API)"""
    __tablename__ = "weather_forecasts"

    id = Column(Integer, primary_key=True, index=True)

    forecast_time = Column(DateTime, nullable=False)  # When the forecast is for
    fetched_at = Column(DateTime, default=datetime.utcnow)  # When we got it

    temp_high = Column(Float)
    temp_low = Column(Float)
    humidity = Column(Integer)

    # Precipitation
    chance_of_rain = Column(Integer)  # %
    rain_amount = Column(Float)  # inches

    # Wind
    wind_speed = Column(Float)
    wind_gust = Column(Float)

    # Conditions
    condition = Column(String(100))  # sunny, cloudy, rain, storm, etc.
    condition_icon = Column(String(50))

    # Sunrise/Sunset
    sunrise = Column(DateTime)
    sunset = Column(DateTime)

    def __repr__(self):
        return f"<WeatherForecast {self.forecast_time.date()}>"
