#!/usr/bin/env python3
"""Enrich seed data in the production database with comprehensive growing information."""
import sqlite3
import sys

DB_PATH = "/opt/levi/backend/data/levi.db"

# Data keyed by seed ID
SEED_DATA = {
    1: {  # Arnica
        "latin_name": "Arnica montana",
        "days_to_germination": "14-28 days",
        "days_to_maturity": "120-150 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12 inches",
        "row_spacing": "18 inches",
        "optimal_germ_temp": "55-65F",
        "light_to_germinate": "Light required",
        "soil_type": "Sandy, well-drained, acidic",
        "ph_range": "5.0-6.5",
        "grow_zones": "4-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Oct-Nov",
        "sow_months": "Feb-Mar, Oct-Nov",
        "height": "12-24 inches",
        "spread": "6-12 inches",
        "special_requirements": "Cold stratification 4 weeks recommended",
        "growing_notes": "Prefers cool conditions. Struggles in hot humid summers. Grow in partial shade in Zone 9b. Needs excellent drainage. Does not tolerate clay or wet soil.",
        "harvest_notes": "Harvest flowers when fully open in morning. Dry quickly in shade. Flowers are ready when petals begin to fade.",
        "medicinal_notes": "EXTERNAL USE ONLY. Anti-inflammatory for bruises, sprains, muscle soreness. Do not apply to broken skin. Homeopathic preparations used internally. Active compounds: sesquiterpene lactones, flavonoids.",
    },
    2: {  # Licorice
        "latin_name": "Glycyrrhiza glabra",
        "days_to_germination": "14-21 days",
        "days_to_maturity": "3-4 years for root harvest",
        "planting_depth": "1/4 inch",
        "spacing": "18-24 inches",
        "row_spacing": "36 inches",
        "optimal_germ_temp": "68-75F",
        "light_to_germinate": "Light helpful",
        "soil_type": "Deep, sandy loam, well-drained",
        "ph_range": "6.0-7.5",
        "grow_zones": "7-10",
        "spring_planting": "Feb-Apr",
        "sow_months": "Feb-Apr",
        "height": "36-48 inches",
        "spread": "18-24 inches",
        "special_requirements": "Scarify seeds or soak 24 hours before planting",
        "growing_notes": "Deep taproot needs loose soil. Spreads by rhizomes. Can become invasive. Needs full sun. Tolerates heat well in Florida. Mulch in summer to retain moisture.",
        "harvest_notes": "Harvest roots after 3-4 years of growth in fall. Dig carefully to preserve root length. Wash and dry roots thoroughly. Can harvest runners from established plants.",
        "medicinal_notes": "Demulcent and expectorant for respiratory issues. Soothes digestive tract. Supports adrenal function. CAUTION: Can raise blood pressure with prolonged use. Avoid if hypertensive. Do not use longer than 6 weeks continuously.",
    },
    3: {  # Burdock
        "latin_name": "Arctium lappa",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "120-150 days (root), biennial",
        "planting_depth": "1/4-1/2 inch",
        "spacing": "6-8 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Deep, loose, well-drained loam",
        "ph_range": "6.0-7.0",
        "grow_zones": "3-10",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Mar, Sep-Oct",
        "harvest_months": "First year fall roots",
        "height": "36-72 inches",
        "spread": "24-36 inches",
        "special_requirements": "Needs deep loose soil (18+ inches) for straight roots",
        "growing_notes": "Biennial. Harvest roots first year for best quality. Deep taproot - raised beds or deeply tilled soil ideal. Full sun to partial shade. Very hardy and low maintenance once established.",
        "harvest_notes": "Harvest first-year roots in fall after frost. Dig deeply to avoid breaking taproot. Roots can be 2+ feet long. Second year plants produce seeds but roots become woody. Young leaf stalks are also edible.",
        "medicinal_notes": "Blood purifier and lymphatic support. Root is alterative and diuretic. Used for skin conditions (acne, eczema, psoriasis). Rich in inulin prebiotic fiber. Seeds used for sore throat. Combines well with dandelion root.",
    },
    4: {  # English Lavender
        "latin_name": "Lavandula angustifolia",
        "days_to_germination": "14-28 days",
        "days_to_maturity": "90-200 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "65-70F",
        "light_to_germinate": "Light required",
        "soil_type": "Sandy, well-drained, alkaline",
        "ph_range": "6.5-8.0",
        "grow_zones": "5-9",
        "spring_planting": "Jan-Mar",
        "fall_planting": "Oct-Nov",
        "sow_months": "Jan-Mar, Oct-Nov",
        "harvest_months": "May-Jul",
        "height": "12-24 inches",
        "spread": "12-18 inches",
        "special_requirements": "Cold stratification 2 weeks improves germination. Excellent drainage critical.",
        "growing_notes": "Struggles in Florida humidity. Best in raised beds with excellent drainage and air circulation. Add sand or gravel to soil. Avoid mulch near crown. Spanish lavender (L. stoechas) may perform better in Zone 9b.",
        "harvest_notes": "Cut flower stems when lower 1/3 of flowers are open. Harvest in morning after dew dries. Bundle and hang upside down in dark, dry area. Flowers retain fragrance for years when dried properly.",
        "medicinal_notes": "Calming and anxiolytic. Essential oil for burns, insomnia, headaches. Tea for nervous tension and digestive upset. Antimicrobial properties. Safe for most people. Avoid concentrated oil internally.",
    },
    5: {  # Tall Mix Bachelor's Button
        "latin_name": "Centaurea cyanus",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "65-85 days",
        "planting_depth": "1/4 inch",
        "spacing": "6-12 inches",
        "row_spacing": "12-18 inches",
        "optimal_germ_temp": "60-65F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.5",
        "grow_zones": "2-11",
        "spring_planting": "Oct-Feb (cool season flower in FL)",
        "fall_planting": "Oct-Nov",
        "sow_months": "Oct-Feb",
        "harvest_months": "Mar-May",
        "height": "24-36 inches",
        "spread": "8-12 inches",
        "growing_notes": "Cool season annual in Florida. Direct sow in fall for spring blooms. Deadhead to prolong flowering. Self-seeds readily. Attracts bees and butterflies. Tolerates poor soil. May need staking.",
        "harvest_notes": "Cut flowers when just opening for longest vase life. Edible flowers - use petals fresh in salads. Flowers dry well for arrangements. Deadhead spent blooms to encourage more flowers.",
    },
    6: {  # Peppermint
        "latin_name": "Mentha x piperita",
        "days_to_germination": "10-16 days",
        "days_to_maturity": "90 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "18-24 inches",
        "row_spacing": "24 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Rich, moist, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "3-11",
        "spring_planting": "Feb-Apr",
        "fall_planting": "Sep-Nov",
        "sow_months": "Feb-Apr, Sep-Nov",
        "harvest_months": "Year-round in Zone 9b",
        "height": "12-36 inches",
        "spread": "24+ inches (spreading)",
        "special_requirements": "INVASIVE - grow in containers to prevent spreading",
        "growing_notes": "Extremely vigorous spreader. Best grown in containers or with root barriers. Partial shade in Florida summer heat. Keep soil consistently moist. Cut back regularly to promote fresh growth. May die back in hottest months but returns.",
        "harvest_notes": "Harvest leaves anytime. Best flavor just before flowering. Cut stems to 1 inch above ground for full harvest - will regrow. Morning harvest has highest essential oil content.",
        "medicinal_notes": "Digestive aid - relieves nausea, gas, bloating, IBS. Menthol is cooling and analgesic. Tea for headaches and sinus congestion. Essential oil for muscle pain topically. Avoid giving to young children. Can reduce milk supply in nursing mothers.",
    },
    7: {  # Marshmallow
        "latin_name": "Althaea officinalis",
        "days_to_germination": "14-21 days",
        "days_to_maturity": "2 years for root harvest",
        "planting_depth": "1/4 inch",
        "spacing": "18-24 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light helpful",
        "soil_type": "Moist, rich, slightly sandy",
        "ph_range": "6.0-8.0",
        "grow_zones": "3-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Oct-Nov",
        "sow_months": "Feb-Mar, Oct-Nov",
        "height": "36-48 inches",
        "spread": "18-24 inches",
        "special_requirements": "Cold stratification 4 weeks recommended for best germination",
        "growing_notes": "Prefers consistently moist soil. Tolerates partial shade. Can struggle in Florida heat - provide afternoon shade. Attractive pink-white flowers. Self-seeds in ideal conditions. Dies back in winter, returns in spring.",
        "harvest_notes": "Harvest roots in fall of second year. Leaves can be harvested first year. Flowers harvested when open. All parts are mucilaginous. Dry roots thoroughly before storage.",
        "medicinal_notes": "Highly mucilaginous - soothes inflamed mucous membranes. Root tea for sore throat, cough, gastritis, UTI. Leaves as poultice for skin inflammation. Safe for children. The original marshmallow candy was made from this root.",
    },
    8: {  # German Chamomile
        "latin_name": "Matricaria chamomilla",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "60-65 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "6-8 inches",
        "row_spacing": "12-18 inches",
        "optimal_germ_temp": "55-65F",
        "light_to_germinate": "Light required",
        "soil_type": "Average, well-drained",
        "ph_range": "5.6-7.5",
        "grow_zones": "3-9",
        "spring_planting": "Oct-Feb (cool season in FL)",
        "fall_planting": "Oct-Nov",
        "sow_months": "Oct-Feb",
        "harvest_months": "Mar-May",
        "height": "12-24 inches",
        "spread": "8-12 inches",
        "growing_notes": "Cool season annual in Florida. Sow in fall for winter/spring harvest. Self-seeds prolifically. Very easy to grow. Full sun to light shade. Tolerates poor soil. Apple-scented foliage.",
        "harvest_notes": "Pick flowers when petals are flat or slightly reflexed. Harvest every 2-3 days for continuous production. Dry flowers in single layer in shade. A chamomile rake makes harvesting easier.",
        "medicinal_notes": "Gentle calming tea safe for children. Anti-inflammatory, antispasmodic. Aids sleep, digestive upset, teething pain. Topically for skin irritation and eye compresses. CAUTION: Avoid if allergic to ragweed/daisy family.",
    },
    9: {  # White Yarrow
        "latin_name": "Achillea millefolium",
        "days_to_germination": "14-21 days",
        "days_to_maturity": "120-180 days first year",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Average to poor, well-drained",
        "ph_range": "5.5-7.0",
        "grow_zones": "3-10",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Mar, Sep-Oct",
        "harvest_months": "Apr-Oct",
        "height": "24-36 inches",
        "spread": "18-24 inches",
        "special_requirements": "Can become invasive via rhizomes",
        "growing_notes": "Very tough and adaptable. Thrives in poor soil - rich soil makes it floppy. Drought tolerant once established. Spreads by rhizomes. Good companion plant - enhances essential oil production in nearby herbs.",
        "harvest_notes": "Harvest flowering tops when in full bloom. Cut whole stems 6 inches from base. Dry in bundles hung upside down. Leaves can be harvested anytime for poultices.",
        "medicinal_notes": "Named for Achilles - classic wound herb. Stops bleeding (styptic), anti-inflammatory. Tea for fever, colds, digestive cramps. Tincture for heavy menstruation. Topical for wounds and nosebleeds. CAUTION: Avoid during pregnancy.",
    },
    10: {  # Thyme
        "latin_name": "Thymus vulgaris",
        "days_to_germination": "14-21 days",
        "days_to_maturity": "85-95 days",
        "planting_depth": "Surface sow, barely cover",
        "spacing": "8-12 inches",
        "row_spacing": "12-18 inches",
        "optimal_germ_temp": "60-70F",
        "light_to_germinate": "Light required",
        "soil_type": "Sandy, well-drained, lean",
        "ph_range": "6.0-8.0",
        "grow_zones": "5-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Nov",
        "sow_months": "Feb-Mar, Sep-Nov",
        "harvest_months": "Year-round in Zone 9b",
        "height": "6-12 inches",
        "spread": "12-18 inches",
        "growing_notes": "Mediterranean herb - needs excellent drainage. Raised beds ideal in Florida. Add sand to soil. Full sun. Low water once established. Woody perennial subshrub. Replace every 3-4 years as plants get leggy.",
        "harvest_notes": "Snip sprigs anytime. Best flavor just before flowering. Cut no more than 1/3 at a time. Dries easily - hang in bundles or use dehydrator. Strips easily from woody stems after drying.",
        "medicinal_notes": "Powerful antimicrobial - thymol is antiseptic. Tea for coughs, bronchitis, sore throat. Antifungal properties. Good for respiratory infections. Safe culinary herb. Thyme honey is prized for medicinal properties.",
    },
    11: {  # Anise Hyssop
        "latin_name": "Agastache foeniculum",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "90-120 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "65-70F",
        "light_to_germinate": "Light required",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "4-10",
        "spring_planting": "Feb-Apr",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Apr, Sep-Oct",
        "harvest_months": "May-Oct",
        "height": "24-48 inches",
        "spread": "12-18 inches",
        "growing_notes": "Outstanding pollinator plant. Licorice-scented leaves and purple flower spikes. Self-seeds readily. Easy to grow. Tolerates heat reasonably well. Full sun to light shade. Deadhead for extended bloom or let self-sow.",
        "harvest_notes": "Harvest leaves anytime for tea. Flower spikes edible and decorative. Cut flowers when 3/4 open. Leaves and flowers dry well for winter tea. Best flavor before full bloom.",
        "medicinal_notes": "Mild digestive aid. Tea for coughs and colds. Traditionally used for fevers. Gentle enough for children. Pleasant licorice flavor makes it a good blending herb in tea formulas.",
    },
    12: {  # Calendula
        "latin_name": "Calendula officinalis",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "45-60 days",
        "planting_depth": "1/4-1/2 inch",
        "spacing": "8-12 inches",
        "row_spacing": "12-18 inches",
        "optimal_germ_temp": "60-70F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "2-11",
        "spring_planting": "Oct-Feb (cool season in FL)",
        "fall_planting": "Oct-Nov",
        "sow_months": "Oct-Feb",
        "harvest_months": "Dec-May",
        "height": "12-24 inches",
        "spread": "12-18 inches",
        "growing_notes": "Cool season annual in Florida. Direct sow in fall. Self-seeds prolifically. Deadhead to prolong flowering. Companion plant - repels some garden pests. Easy to grow. Full sun.",
        "harvest_notes": "Pick flowers when fully open, harvest frequently to promote more blooms. Dry whole flowers in single layer. Petals should be sticky/resinous when fresh (indicates high medicinal content). Harvest every 2-3 days.",
        "medicinal_notes": "Premier skin healing herb. Anti-inflammatory, antifungal, wound healing. Used in salves, oils, creams for cuts, burns, rashes, eczema. Internal tea for digestive inflammation. Lymphatic support. Safe for babies and sensitive skin.",
    },
    13: {  # Blue Skullcap
        "latin_name": "Scutellaria lateriflora",
        "days_to_germination": "14-28 days",
        "days_to_maturity": "120-150 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "65-70F",
        "light_to_germinate": "Light required",
        "soil_type": "Moist, rich, slightly acidic",
        "ph_range": "5.5-7.0",
        "grow_zones": "4-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Oct-Nov",
        "sow_months": "Feb-Mar, Oct-Nov",
        "height": "12-24 inches",
        "spread": "12-18 inches",
        "special_requirements": "Cold stratification 2 weeks. Needs consistent moisture.",
        "growing_notes": "Native North American herb. Prefers partial shade and moist conditions - good for rain gardens. Spreading perennial. Small blue flowers. Can grow near ponds or in boggy areas. Benefits from mulching.",
        "harvest_notes": "Harvest aerial parts (stems, leaves, flowers) during flowering. Cut to 4 inches above ground. Can harvest 2-3 times per season. Dry quickly to preserve blue color.",
        "medicinal_notes": "Premier nervine herb for anxiety, nervous tension, insomnia. Antispasmodic. Helps with withdrawal symptoms. Tincture is preferred preparation. Combines well with valerian and passionflower. Safe for most adults at recommended doses.",
    },
    14: {  # Catnip
        "latin_name": "Nepeta cataria",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "80-90 days",
        "planting_depth": "1/8 inch",
        "spacing": "18-24 inches",
        "row_spacing": "24 inches",
        "optimal_germ_temp": "60-70F",
        "light_to_germinate": "Light required",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.5",
        "grow_zones": "3-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Nov",
        "sow_months": "Feb-Mar, Sep-Nov",
        "harvest_months": "Apr-Nov",
        "height": "24-36 inches",
        "spread": "18-24 inches",
        "special_requirements": "Protect from cats until established - they will roll on seedlings",
        "growing_notes": "Very easy to grow, can become invasive via self-seeding. Full sun to part shade. Drought tolerant once established. Cats are attracted to bruised leaves. Mosquito repellent properties. Member of mint family.",
        "harvest_notes": "Harvest leaves and flowering tops when in bloom. Cut stems 6 inches above ground. Dry in shade. Potency diminishes in dried herb over time - use within 6 months.",
        "medicinal_notes": "Mild sedative and calming herb. Tea for children's fevers, colic, and restlessness. Digestive aid. Helps with insomnia. Very safe for children. Nepetalactone is the compound that affects cats.",
    },
    15: {  # Siberian Meadowsweet
        "latin_name": "Filipendula palmata",
        "days_to_germination": "14-30 days",
        "days_to_maturity": "Second year flowering",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "18-24 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "60-65F",
        "light_to_germinate": "Light required",
        "soil_type": "Rich, moist, humus-rich",
        "ph_range": "5.5-7.0",
        "grow_zones": "3-8",
        "spring_planting": "Jan-Feb (before heat)",
        "sow_months": "Jan-Feb, Nov-Dec",
        "height": "24-48 inches",
        "spread": "18-24 inches",
        "special_requirements": "Cold stratification 4-6 weeks required. Needs consistent moisture.",
        "growing_notes": "Prefers cool, moist conditions - challenging in Florida heat. Best in partial to full shade with consistent moisture. Bog garden or rain garden plant. Beautiful pink plume flowers. May go dormant in summer heat.",
        "harvest_notes": "Harvest flowering tops and leaves when flowers are open. Dry quickly in shade. Root can also be harvested in fall of second year.",
        "medicinal_notes": "Contains natural salicylates (aspirin-like compounds). Pain relief, anti-inflammatory, fever reducer. Tea for headaches, joint pain, digestive upset. Gentler on stomach than aspirin. CAUTION: Avoid if allergic to aspirin or taking blood thinners.",
    },
    16: {  # St. John's Wort
        "latin_name": "Hypericum perforatum",
        "days_to_germination": "10-21 days",
        "days_to_maturity": "120 days first year",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Average to poor, well-drained",
        "ph_range": "5.5-7.0",
        "grow_zones": "3-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Oct-Nov",
        "sow_months": "Feb-Mar, Oct-Nov",
        "harvest_months": "Jun-Aug (around St. John's Day)",
        "height": "12-36 inches",
        "spread": "12-18 inches",
        "special_requirements": "Cold stratification 2 weeks improves germination",
        "growing_notes": "Full sun for best medicinal potency. Drought tolerant once established. Can spread aggressively - considered invasive in some areas. Leaves have tiny perforations visible when held to light. Yellow flowers.",
        "harvest_notes": "Harvest flowering tops when buds are just opening - they should stain fingers red/purple when crushed. This red color indicates hypericin content. Tincture fresh flowers in oil for best results.",
        "medicinal_notes": "Well-studied for mild to moderate depression. Nerve repair and pain relief. Anti-inflammatory. Red oil topically for nerve pain, burns, bruises. MAJOR DRUG INTERACTIONS: reduces effectiveness of birth control, blood thinners, HIV meds, many others. Causes photosensitivity.",
    },
    17: {  # True Dandelion
        "latin_name": "Taraxacum officinale",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "85-95 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "6-8 inches",
        "row_spacing": "12 inches",
        "optimal_germ_temp": "55-65F",
        "light_to_germinate": "Light required",
        "soil_type": "Any, adaptable",
        "ph_range": "5.5-8.0",
        "grow_zones": "3-10",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Nov",
        "sow_months": "Feb-Mar, Sep-Nov",
        "harvest_months": "Year-round leaves, spring/fall roots",
        "height": "6-12 inches",
        "spread": "6-12 inches",
        "growing_notes": "Extremely easy to grow. Deep taproot breaks up compacted soil. Every part is useful. Cooler weather produces less bitter leaves. Full sun to partial shade. Can grow as a cultivated green.",
        "harvest_notes": "Harvest young leaves for salads (less bitter). Roots best harvested in fall when energy stored in root. Flowers for wine, fritters, or infused oil. Roots can be roasted as coffee substitute.",
        "medicinal_notes": "Liver tonic and gentle detoxifier. Root is bitter digestive stimulant. Leaf is potassium-sparing diuretic. Rich in vitamins A, C, K, minerals. Root for liver support, leaf for kidney/fluid retention. Safe for most people. Avoid if allergic to daisy family.",
    },
    18: {  # Common Mullein
        "latin_name": "Verbascum thapsus",
        "days_to_germination": "14-30 days",
        "days_to_maturity": "Biennial - flowers second year",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "18-24 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Poor, dry, well-drained",
        "ph_range": "5.5-7.5",
        "grow_zones": "3-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Mar, Sep-Oct",
        "height": "48-72 inches (flower stalk)",
        "spread": "18-24 inches",
        "growing_notes": "Biennial - fuzzy rosette first year, tall flower spike second year. Thrives in poor soil. Drought tolerant. Full sun. Self-seeds readily. Large velvety leaves. Impressive architectural plant.",
        "harvest_notes": "Harvest leaves first year, flowers second year. Pick individual flowers when open. Strain flower tea through cloth to remove tiny hairs. Leaves can be dried for tea year-round.",
        "medicinal_notes": "Premier respiratory herb. Leaf tea for coughs, bronchitis, asthma. Flower oil for earaches (warm drops in ear). Demulcent and expectorant. Leaf smoke historically used for lung congestion. Very safe. Strain tea through coffee filter to remove irritating leaf hairs.",
    },
    19: {  # Holy Basil
        "latin_name": "Ocimum tenuiflorum",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "60-90 days",
        "planting_depth": "1/4 inch",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "70-80F",
        "light_to_germinate": "Light helpful",
        "soil_type": "Rich, moist, well-drained",
        "ph_range": "6.0-7.5",
        "grow_zones": "9-11",
        "spring_planting": "Mar-May",
        "fall_planting": "Aug-Sep",
        "sow_months": "Mar-Sep",
        "harvest_months": "May-Nov",
        "height": "12-24 inches",
        "spread": "12-18 inches",
        "growing_notes": "Tulsi - sacred herb in Ayurveda. Thrives in Florida heat and humidity. Full sun. Pinch flowers to promote bushy leaf growth. Can be perennial in Zone 9b. Three main types: Rama (green), Krishna (purple), Vana (wild).",
        "harvest_notes": "Harvest leaves regularly, pinching stems above a leaf node. Cut before flowering for best flavor. Can harvest entire plant leaving 4 inches for regrowth. Best used fresh but dries adequately.",
        "medicinal_notes": "Premier adaptogenic herb in Ayurveda. Reduces cortisol and stress response. Supports immune function, respiratory health. Anti-inflammatory, antioxidant. Daily tea for general wellness. Helps regulate blood sugar. Safe for long-term use.",
    },
    20: {  # Angelica
        "latin_name": "Angelica archangelica",
        "days_to_germination": "14-28 days",
        "days_to_maturity": "Biennial - 2 years",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "24-36 inches",
        "row_spacing": "36-48 inches",
        "optimal_germ_temp": "60-65F",
        "light_to_germinate": "Light required",
        "soil_type": "Rich, moist, deep",
        "ph_range": "5.5-7.0",
        "grow_zones": "4-9",
        "spring_planting": "Jan-Feb (needs cold)",
        "sow_months": "Nov-Feb",
        "height": "48-72 inches",
        "spread": "24-36 inches",
        "special_requirements": "Seeds must be FRESH (viability drops quickly). Cold stratification required. Use seed within a few months of harvest.",
        "growing_notes": "Large dramatic plant. Prefers cool, moist conditions - challenging in Florida. Best in partial shade with consistent moisture. Biennial but may persist if flower stalks removed. Monocarpic - dies after seeding.",
        "harvest_notes": "Harvest stems for candying in spring of second year. Roots in fall of first year. Seeds when ripe. All parts aromatic. Stems can be candied for confections.",
        "medicinal_notes": "Warming digestive herb. Carminative and bitter tonic. Used for poor appetite, gas, bloating. Traditionally used for respiratory congestion and colds. CAUTION: Photosensitizing - avoid sun exposure after use. Do not use during pregnancy. Can be confused with poisonous water hemlock - be certain of identification.",
    },
    21: {  # Stinging Nettle
        "latin_name": "Urtica dioica",
        "days_to_germination": "10-14 days",
        "days_to_maturity": "80-90 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Rich, moist, nitrogen-rich",
        "ph_range": "6.0-7.0",
        "grow_zones": "3-10",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Oct-Nov",
        "sow_months": "Feb-Mar, Oct-Nov",
        "harvest_months": "Spring growth (before flowering)",
        "height": "36-72 inches",
        "spread": "18-24 inches (spreading)",
        "special_requirements": "WEAR GLOVES when handling - stinging hairs. Cold stratification 2 weeks helps.",
        "growing_notes": "Extremely nutritious edible green. Spreads by rhizomes - can be invasive. Prefers rich, moist soil. Partial shade in Florida. Stinging hairs neutralized by cooking, drying, or blending. Indicator of nitrogen-rich soil.",
        "harvest_notes": "Harvest young tops (top 4-6 inches) in spring before flowering. Wear thick gloves. Cooking or drying completely neutralizes sting. Can cut back for multiple harvests. Older leaves become gritty from cystoliths.",
        "medicinal_notes": "Nutritive tonic - high in iron, calcium, silica, vitamins A and C. Antihistamine for seasonal allergies (freeze-dried caps or fresh juice). Root used for BPH/prostate health. Tea as general mineral tonic. Galactagogue (promotes milk production). Very safe as food and tea.",
    },
    22: {  # Valerian
        "latin_name": "Valeriana officinalis",
        "days_to_germination": "14-21 days",
        "days_to_maturity": "Second year root harvest",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "60-68F",
        "light_to_germinate": "Light required",
        "soil_type": "Rich, moist, humus-rich",
        "ph_range": "5.5-7.0",
        "grow_zones": "4-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Oct-Nov",
        "sow_months": "Feb-Mar, Oct-Nov",
        "harvest_months": "Fall root harvest (2nd year)",
        "height": "36-60 inches",
        "spread": "18-24 inches",
        "special_requirements": "Fresh seed germinates best. Use seed less than 1 year old.",
        "growing_notes": "Tall perennial with fragrant white/pink flower clusters. Prefers partial shade in Florida. Keep soil consistently moist. Attractive to cats (similar to catnip). Self-seeds readily. Flowers are sweetly fragrant but roots smell strong.",
        "harvest_notes": "Harvest roots in fall of second year after tops die back. Wash thoroughly and chop before drying. Dried root has very strong, distinctive odor. Roots are most potent when dried.",
        "medicinal_notes": "Premier sleep herb. Sedative and anxiolytic. Improves sleep quality without morning grogginess for most people. Also antispasmodic for muscle tension and cramps. Combines well with hops, passionflower, skullcap. Note: paradoxical stimulating effect in about 10% of people. Start with low dose.",
    },
    23: {  # Rosemary
        "latin_name": "Salvia rosmarinus",
        "days_to_germination": "14-28 days",
        "days_to_maturity": "90-120 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "24-36 inches",
        "row_spacing": "36-48 inches",
        "optimal_germ_temp": "65-70F",
        "light_to_germinate": "Light required",
        "soil_type": "Sandy, well-drained, lean",
        "ph_range": "6.0-7.5",
        "grow_zones": "7-10",
        "spring_planting": "Feb-Apr",
        "fall_planting": "Sep-Nov",
        "sow_months": "Feb-Apr, Sep-Nov",
        "harvest_months": "Year-round in Zone 9b",
        "height": "24-48 inches",
        "spread": "24-48 inches",
        "growing_notes": "Excellent in Florida - thrives in heat and sandy soil. Full sun, excellent drainage essential. Drought tolerant once established. Avoid overwatering. Can grow into a large shrub in Zone 9b. Blue flowers attract bees.",
        "harvest_notes": "Snip sprigs anytime. Cut no more than 1/3 of plant at once. Stems are woody - strip leaves for cooking. Dries very well. Can harvest year-round in mild climates.",
        "medicinal_notes": "Improves memory and cognitive function (carnosic acid). Circulatory stimulant. Antioxidant and anti-inflammatory. Traditional hair rinse for dark hair. Topical oil for muscle pain. Safe in culinary amounts. Avoid therapeutic doses during pregnancy.",
    },
    24: {  # Echinacea Purple Coneflower
        "latin_name": "Echinacea purpurea",
        "days_to_germination": "10-21 days",
        "days_to_maturity": "120-180 days first year",
        "planting_depth": "1/4 inch",
        "spacing": "18-24 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light helpful",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "3-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Mar, Sep-Oct",
        "harvest_months": "Jul-Sep flowers; fall roots",
        "height": "24-48 inches",
        "spread": "18-24 inches",
        "special_requirements": "Cold stratification 4 weeks improves germination significantly",
        "growing_notes": "Native wildflower. Full sun preferred. Drought tolerant once established. Beautiful purple-pink daisy flowers. Attracts butterflies and bees. Leave seed heads for goldfinches. May be short-lived perennial in Florida heat.",
        "harvest_notes": "Harvest roots in fall of 3rd year for strongest medicine. Flowers and leaves can be harvested first year. Fresh plant tincture is strongest. Tongue should tingle when tasting good echinacea.",
        "medicinal_notes": "Premier immune stimulant. Take at first sign of cold/flu, not as daily preventive. Increases white blood cell activity. Anti-inflammatory. Root tincture most potent. Combine with elderberry for synergistic immune support. CAUTION: Avoid with autoimmune conditions. Generally safe for short-term use.",
    },
    25: {  # Cayenne Long Red Thin Pepper
        "latin_name": "Capsicum annuum 'Long Red Thin Cayenne'",
        "days_to_germination": "10-14 days",
        "days_to_maturity": "70-80 days",
        "planting_depth": "1/4 inch",
        "spacing": "18-24 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "75-85F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Rich, well-drained loam",
        "ph_range": "6.0-6.8",
        "grow_zones": "4-11",
        "spring_planting": "Feb-Apr",
        "fall_planting": "Aug-Sep",
        "sow_months": "Feb-Apr, Aug-Sep",
        "harvest_months": "Jun-Nov",
        "indoor_start": "6-8 weeks before last frost",
        "height": "24-36 inches",
        "spread": "18-24 inches",
        "growing_notes": "Thrives in Florida heat. Full sun. Rich soil with good drainage. Keep consistently watered during fruit set. Mulch to retain moisture. Can overwinter in Zone 9b. 30,000-50,000 Scoville units.",
        "harvest_notes": "Harvest when fully red for best heat and flavor. Can pick green but less flavorful. Dry easily - string on thread or use dehydrator. Grind dried peppers for cayenne powder. Wear gloves when handling hot peppers.",
        "medicinal_notes": "Circulatory stimulant - increases blood flow. Topical pain relief (capsaicin cream). Helps stop bleeding when applied to wounds. Aids digestion. Metabolic booster. Can be used as crisis herb to intensify action of other herbs. Start with small amounts internally.",
    },
    26: {  # Broadleaf Sage
        "latin_name": "Salvia officinalis",
        "days_to_germination": "10-21 days",
        "days_to_maturity": "75-90 days",
        "planting_depth": "1/4 inch",
        "spacing": "18-24 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "60-70F",
        "light_to_germinate": "Light helpful",
        "soil_type": "Sandy, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "4-10",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Nov",
        "sow_months": "Feb-Mar, Sep-Nov",
        "harvest_months": "Year-round in Zone 9b",
        "height": "18-30 inches",
        "spread": "18-24 inches",
        "growing_notes": "Mediterranean herb. Needs excellent drainage in Florida. Raised beds with sandy soil ideal. Full sun. Drought tolerant once established. Can get leggy - prune regularly. Replace every 3-4 years.",
        "harvest_notes": "Harvest leaves anytime. Best flavor before flowering. Do not harvest more than 1/3 at once in first year. Dries easily and retains flavor well. Blue-purple flowers are also edible.",
        "medicinal_notes": "Sore throat remedy - gargle sage tea. Antimicrobial and astringent. Reduces excessive sweating (night sweats, hot flashes). Digestive aid. CAUTION: Contains thujone - do not use therapeutic doses during pregnancy or for extended periods. Culinary amounts are safe.",
    },
    27: {  # Blue Vervain
        "latin_name": "Verbena hastata",
        "days_to_germination": "14-30 days",
        "days_to_maturity": "120-150 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "60-70F",
        "light_to_germinate": "Light required",
        "soil_type": "Moist, rich, adaptable",
        "ph_range": "6.0-7.0",
        "grow_zones": "3-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Oct-Nov",
        "sow_months": "Feb-Mar, Oct-Nov",
        "harvest_months": "Jul-Sep during flowering",
        "height": "24-60 inches",
        "spread": "12-18 inches",
        "special_requirements": "Cold stratification 4 weeks required for good germination",
        "growing_notes": "Native perennial. Attractive blue flower spikes. Excellent pollinator plant. Prefers moist soil - good for rain gardens. Full sun to part shade. Self-seeds moderately. Good butterfly plant.",
        "harvest_notes": "Harvest aerial parts (leaves, flowers, stems) during peak bloom. Cut upper 1/3 of plant. Dry quickly in shade. Can harvest 1-2 times per season.",
        "medicinal_notes": "Strong nervine for tension and stress held in the body. Bitter digestive tonic. Traditionally used for depression and melancholy. Antispasmodic. Promotes sweating during fevers. Strong bitter taste - tincture preferred over tea. CAUTION: Avoid during pregnancy - uterine stimulant.",
    },
    28: {  # Florence Fennel
        "latin_name": "Foeniculum vulgare var. azoricum",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "65-90 days",
        "planting_depth": "1/4 inch",
        "spacing": "6-12 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "60-70F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Rich, well-drained, fertile",
        "ph_range": "6.0-7.0",
        "grow_zones": "4-10",
        "spring_planting": "Oct-Feb (cool season in FL)",
        "fall_planting": "Oct-Nov",
        "sow_months": "Oct-Feb",
        "harvest_months": "Feb-May",
        "height": "24-36 inches",
        "spread": "12-18 inches",
        "growing_notes": "Cool season crop in Florida. Direct sow - does not transplant well due to taproot. Bolts quickly in heat. Succession plant every 2-3 weeks. Hill soil around bulb base to blanch. Full sun.",
        "harvest_notes": "Harvest bulb when tennis ball sized. Cut at soil level. Fronds and seeds also edible. Seeds harvested when brown and dry on plant. All parts have anise flavor.",
        "medicinal_notes": "Excellent digestive carminative - relieves gas, bloating, colic. Safe for infants as gripe water. Galactagogue (promotes breast milk). Mild estrogenic properties. Seed tea after meals for digestion. Anti-inflammatory for eyes as wash.",
    },
    29: {  # Ashwagandha
        "latin_name": "Withania somnifera",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "150-180 days (root harvest)",
        "planting_depth": "1/4 inch",
        "spacing": "24-36 inches",
        "row_spacing": "36 inches",
        "optimal_germ_temp": "70-80F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Sandy, well-drained, lean",
        "ph_range": "6.0-7.5",
        "grow_zones": "8-11",
        "spring_planting": "Mar-May",
        "fall_planting": "Aug-Sep",
        "sow_months": "Mar-Sep",
        "harvest_months": "Fall root harvest",
        "height": "24-36 inches",
        "spread": "24-36 inches",
        "growing_notes": "Thrives in Florida heat. Full sun. Sandy soil with minimal water once established. Nightshade family - small lantern-like fruits. Can be perennial in Zone 9b. Does NOT like wet feet. Drought tolerant.",
        "harvest_notes": "Harvest roots after 150-180 days when leaves start yellowing. Whole plant can be harvested. Roots should be washed, sliced, and dried. Berries are also used medicinally in Ayurveda.",
        "medicinal_notes": "Premier Ayurvedic adaptogen. Reduces cortisol and anxiety. Improves sleep quality (name means 'smell of horse' and 'gives strength of horse'). Supports thyroid function. Anti-inflammatory. Enhances stamina and endurance. Safe for long-term use. CAUTION: Nightshade family - avoid if sensitive. May increase thyroid hormone levels.",
    },
    30: {  # Red Clover
        "latin_name": "Trifolium pratense",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "60-90 days to flower",
        "planting_depth": "1/4 inch",
        "spacing": "6-8 inches",
        "row_spacing": "12 inches",
        "optimal_germ_temp": "60-70F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Average, adaptable",
        "ph_range": "6.0-7.0",
        "grow_zones": "3-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Nov",
        "sow_months": "Sep-Mar",
        "harvest_months": "Apr-Jun flowers",
        "height": "12-24 inches",
        "spread": "12-18 inches (spreading)",
        "growing_notes": "Nitrogen-fixing legume - improves soil fertility. Good cover crop and living mulch. Full sun to light shade. Easy to grow. Attracts bees. Cool season in Florida. Can be mowed as ground cover.",
        "harvest_notes": "Harvest flower heads when fully open and bright pink/red. Dry quickly to preserve color. Can harvest leaves as well. Flowers lose color when over-dried.",
        "medicinal_notes": "Blood purifier and lymphatic cleanser. Traditional cancer-prevention herb (Hoxsey formula). Rich in isoflavones - used for menopause symptoms. Respiratory support for coughs. Topical for skin conditions. Generally safe. CAUTION: Mild blood thinner - discontinue before surgery. Estrogenic - avoid with hormone-sensitive conditions.",
    },
    31: {  # Milk Thistle
        "latin_name": "Silybum marianum",
        "days_to_germination": "10-21 days",
        "days_to_maturity": "120-150 days",
        "planting_depth": "1/4 inch",
        "spacing": "24-36 inches",
        "row_spacing": "36 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Average, well-drained",
        "ph_range": "5.5-7.5",
        "grow_zones": "5-10",
        "spring_planting": "Oct-Feb (cool season in FL)",
        "fall_planting": "Oct-Nov",
        "sow_months": "Oct-Feb",
        "harvest_months": "May-Jun seeds",
        "height": "36-60 inches",
        "spread": "24-36 inches",
        "special_requirements": "Spiny plant - wear gloves. Can self-seed aggressively.",
        "growing_notes": "Dramatic thistle with white-marbled leaves. Cool season annual in Florida. Full sun. Drought tolerant. Very easy to grow. Can become weedy from self-seeding. Attractive purple flowers. Spiny leaves.",
        "harvest_notes": "Harvest seed heads when flowers dry and white pappus appears. Cut heads into paper bag - seeds fall out. Seeds are small and hard. Can be ground in coffee grinder for use.",
        "medicinal_notes": "Premier liver protective herb. Silymarin compound protects and regenerates liver cells. Used for liver disease, hepatitis, fatty liver, alcohol damage. Antioxidant. Supports detoxification. Ground seeds in smoothies or capsules. Very safe with minimal side effects.",
    },
    32: {  # Lemon Mint Bee Balm
        "latin_name": "Monarda citriodora",
        "days_to_germination": "10-21 days",
        "days_to_maturity": "80-100 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "65-70F",
        "light_to_germinate": "Light required",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "4-10",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Mar, Sep-Oct",
        "harvest_months": "May-Sep",
        "height": "18-30 inches",
        "spread": "12-18 inches",
        "growing_notes": "Outstanding pollinator magnet - bees, hummingbirds, butterflies. Lemon-scented foliage. Tiered whorls of lavender flowers. Easy annual/short-lived perennial. Full sun. Self-seeds readily. Drought tolerant once established.",
        "harvest_notes": "Harvest leaves and flowers when in bloom. Excellent fresh or dried tea. Cut stems above a leaf node for regrowth. Flowers are edible and decorative.",
        "medicinal_notes": "Contains thymol - antimicrobial. Tea for digestive upset and colds. Traditional remedy for respiratory infections. Pleasant lemony flavor makes good daily tea. Milder than other Monarda species.",
    },
    33: {  # Florida Grove Pepper
        "latin_name": "Capsicum annuum 'Florida Grove'",
        "days_to_germination": "10-14 days",
        "days_to_maturity": "75-90 days",
        "planting_depth": "1/4 inch",
        "spacing": "18-24 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "75-85F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Rich, well-drained loam",
        "ph_range": "6.0-6.8",
        "grow_zones": "8-11",
        "spring_planting": "Feb-Apr",
        "fall_planting": "Aug-Sep",
        "sow_months": "Feb-Apr, Aug-Sep",
        "harvest_months": "Jun-Nov",
        "indoor_start": "6-8 weeks before transplanting",
        "height": "24-36 inches",
        "spread": "18-24 inches",
        "growing_notes": "Florida-adapted hot pepper. Thrives in heat and humidity. Full sun. Rich soil. Consistent watering during fruiting. Can overwinter in Zone 9b. Mulch well.",
        "harvest_notes": "Harvest when peppers reach desired color and heat level. Regular picking encourages more fruit production. Can be dried, pickled, or used fresh.",
    },
    34: {  # Florida Velvet Bean
        "latin_name": "Mucuna pruriens",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "90-120 days",
        "planting_depth": "1 inch",
        "spacing": "24-36 inches",
        "row_spacing": "48-72 inches",
        "optimal_germ_temp": "75-85F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Average, well-drained",
        "ph_range": "5.5-7.0",
        "grow_zones": "9-11",
        "spring_planting": "Mar-Jun",
        "sow_months": "Mar-Jun",
        "harvest_months": "Aug-Nov",
        "height": "Vine to 15+ feet",
        "spread": "Spreading vine",
        "special_requirements": "Needs strong trellis or support. Seed pods have irritating hairs - wear gloves. Scarify or soak seeds 24 hours.",
        "growing_notes": "Vigorous tropical vine. Excellent nitrogen fixer and cover crop. Historically grown in Florida as cattle feed and soil improvement. Needs sturdy support. Beautiful purple flowers. CAUTION: Seed pod hairs are extremely itchy.",
        "harvest_notes": "Harvest dry seed pods when brown. Wear long sleeves and gloves - pod hairs cause intense itching. Seeds are processed (roasted/boiled) before use. Never eat raw seeds.",
        "medicinal_notes": "Contains L-DOPA, a dopamine precursor. Used in Ayurveda for mood, libido, and neurological support. Research supports use for Parkinson's symptoms. Also adaptogenic. CAUTION: Can interact with dopamine medications. Seeds must be properly processed - raw seeds contain anti-nutritional factors.",
    },
    35: {  # Florida Red Everglade Tomato
        "latin_name": "Solanum lycopersicum 'Everglades'",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "60-70 days",
        "planting_depth": "1/4 inch",
        "spacing": "36-48 inches",
        "row_spacing": "48-60 inches",
        "optimal_germ_temp": "70-80F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Rich, well-drained, fertile",
        "ph_range": "6.0-6.8",
        "grow_zones": "8-11",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Aug-Sep",
        "sow_months": "Feb-Mar, Aug-Sep",
        "harvest_months": "May-Nov",
        "indoor_start": "6-8 weeks before transplanting",
        "height": "Indeterminate vine 6-10 feet",
        "spread": "36-48 inches",
        "growing_notes": "Florida heirloom cherry tomato. Extremely heat tolerant - sets fruit in high temperatures when other tomatoes fail. Disease resistant. Vigorous indeterminate vine needs strong support. Self-seeds readily. Produces prolifically.",
        "harvest_notes": "Pick when fully red for best flavor. Small cherry-sized fruits. Very prolific - check daily. Self-seeds aggressively in warm climates. Flavor is sweet and intense.",
    },
    36: {  # Candlestick Senna
        "latin_name": "Senna alata",
        "days_to_germination": "14-30 days",
        "days_to_maturity": "120-180 days",
        "planting_depth": "1/4 inch",
        "spacing": "48-72 inches",
        "row_spacing": "72 inches",
        "optimal_germ_temp": "75-85F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Average, adaptable",
        "ph_range": "5.5-7.5",
        "grow_zones": "9-11",
        "spring_planting": "Mar-May",
        "sow_months": "Mar-May",
        "harvest_months": "Leaves year-round",
        "height": "72-120 inches",
        "spread": "48-72 inches",
        "special_requirements": "Scarify or nick seed coat, or soak in hot water 24 hours",
        "growing_notes": "Large tropical shrub with dramatic candle-like yellow flower spikes. Thrives in Florida heat. Fast growing. Can freeze back in Zone 9b but regrows from roots. Full sun. Butterfly host plant (sulphurs). Also called Candle Bush.",
        "harvest_notes": "Harvest leaves as needed for medicinal use. Flowers are ornamental. Seeds form in long flat pods.",
        "medicinal_notes": "Traditional tropical remedy for ringworm and fungal skin infections (leaves crushed as poultice). Strong laxative - leaves and pods. Used cautiously for constipation. CAUTION: Do not use internally during pregnancy. Strong purgative action - use sparingly.",
    },
    37: {  # Longevity Spinach
        "latin_name": "Gynura procumbens",
        "days_to_germination": "Usually propagated by cuttings",
        "days_to_maturity": "60-90 days from cutting",
        "planting_depth": "Stem cuttings in moist soil",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "70-85F",
        "soil_type": "Rich, moist, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "9-11",
        "spring_planting": "Mar-Oct",
        "sow_months": "Year-round in Zone 9b",
        "harvest_months": "Year-round in Zone 9b",
        "height": "12-24 inches (spreading/trailing)",
        "spread": "24-36 inches",
        "growing_notes": "Tropical perennial green from Southeast Asia. Grows easily from stem cuttings - just stick in moist soil. Partial shade preferred in Florida. Keep moist. Can grow as groundcover or in hanging baskets. Frost tender but regrows from roots in Zone 9b.",
        "harvest_notes": "Pick individual leaves or cut stems back to 4 inches. Eat raw in salads or cooked. Mild, slightly mucilaginous texture. Harvest regularly to promote bushy growth. Very productive once established.",
        "medicinal_notes": "Used in traditional Asian medicine for diabetes management - shown to lower blood sugar. Anti-inflammatory, antioxidant. Used for high blood pressure and cholesterol. Eaten daily as food medicine in Southeast Asia. Generally safe as food but monitor blood sugar if diabetic.",
    },
    38: {  # Jack Bean
        "latin_name": "Canavalia ensiformis",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "90-120 days",
        "planting_depth": "1-2 inches",
        "spacing": "12-18 inches",
        "row_spacing": "36-48 inches",
        "optimal_germ_temp": "70-85F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Average, adaptable, well-drained",
        "ph_range": "5.5-7.0",
        "grow_zones": "8-11",
        "spring_planting": "Mar-Jun",
        "sow_months": "Mar-Jun",
        "harvest_months": "Jul-Nov",
        "height": "Bush to 36 inches or vine to 10 feet",
        "spread": "24-36 inches",
        "growing_notes": "Tropical legume and excellent cover crop. Fixes nitrogen heavily. Very heat tolerant. Drought tolerant once established. Can be grown as bush type or climbing vine. Suppresses weeds. Good for soil building.",
        "harvest_notes": "Young pods edible when small (under 4 inches). Mature seeds must be thoroughly cooked. Used primarily as cover crop/green manure in modern agriculture. Seeds harvested when pods dry.",
    },
    39: {  # Seminole Pumpkin
        "latin_name": "Cucurbita moschata 'Seminole'",
        "days_to_germination": "7-10 days",
        "days_to_maturity": "90-120 days",
        "planting_depth": "1 inch",
        "spacing": "48-72 inches",
        "row_spacing": "72-96 inches",
        "optimal_germ_temp": "75-85F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Rich, well-drained, fertile",
        "ph_range": "6.0-6.8",
        "grow_zones": "8-11",
        "spring_planting": "Mar-May",
        "fall_planting": "Aug",
        "sow_months": "Mar-May, Aug",
        "harvest_months": "Jul-Nov",
        "height": "Vine to 20+ feet",
        "spread": "Spreading vine 10-20 feet",
        "growing_notes": "Florida heritage squash grown by Seminole people for centuries. Extremely heat, humidity, and pest resistant. Vines climb trees naturally. Very vigorous. Resistant to vine borers. Stores for months without refrigeration. THE pumpkin for Florida.",
        "harvest_notes": "Harvest when skin is hard and stem begins to dry. Can store 3-6 months at room temperature. Flesh is sweet, similar to butternut squash. Seeds are also edible roasted. Cut from vine with stem attached.",
    },
    40: {  # Giant Amaranth
        "latin_name": "Amaranthus cruentus",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "90-120 days (grain), 40-50 (greens)",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "70-80F",
        "light_to_germinate": "Light required",
        "soil_type": "Rich, well-drained",
        "ph_range": "6.0-7.5",
        "grow_zones": "4-11",
        "spring_planting": "Mar-Jun",
        "sow_months": "Mar-Jun",
        "harvest_months": "Greens: May-Sep, Grain: Sep-Nov",
        "height": "48-96 inches",
        "spread": "18-36 inches",
        "growing_notes": "Dual purpose - young leaves as greens, mature seed heads as grain. Thrives in Florida heat. Full sun. Dramatic red/purple seed plumes. Very drought tolerant once established. Self-seeds readily. Easy to grow.",
        "harvest_notes": "Harvest young leaves anytime for cooking (like spinach). For grain, let seed heads mature and dry on plant. Cut heads and thresh seeds. Seeds are tiny but produced abundantly. Bend seed heads over bucket and rub to release seeds.",
    },
    41: {  # Moringa
        "latin_name": "Moringa oleifera",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "First harvest 60-90 days",
        "planting_depth": "1 inch",
        "spacing": "36-60 inches",
        "row_spacing": "60-96 inches",
        "optimal_germ_temp": "75-85F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Sandy, well-drained, tolerates poor soil",
        "ph_range": "6.0-7.5",
        "grow_zones": "9-11",
        "spring_planting": "Mar-Jun",
        "sow_months": "Mar-Jun",
        "harvest_months": "Year-round leaves in Zone 9b",
        "height": "120-180+ inches (tree)",
        "spread": "60-120 inches",
        "special_requirements": "Freezes to ground in Zone 9b but regrows rapidly. Can be coppiced (cut back) to keep manageable size.",
        "growing_notes": "Fastest growing tree - can reach 10+ feet first year. Thrives in Florida heat. Very drought tolerant. Sandy soil preferred. Cut back to maintain hedge form and promote leaf production. Freezes back at 32F but resprouts vigorously from roots.",
        "harvest_notes": "Harvest leaves by stripping from stems. Young pods (drumsticks) edible cooked. Flowers edible. Seeds pressed for ben oil. Can harvest leaves continuously if kept pruned. Dry leaves quickly in shade for powder.",
        "medicinal_notes": "Superfood tree - leaves are exceptionally nutrient dense. High in protein, iron, calcium, vitamins A and C. Anti-inflammatory, antioxidant. Supports blood sugar regulation. Leaf powder used as nutritional supplement. Seeds purify water. All parts used in traditional medicine. Generally safe as food.",
    },
    42: {  # Speckled Southern Pea
        "latin_name": "Vigna unguiculata 'Speckled'",
        "days_to_germination": "7-10 days",
        "days_to_maturity": "60-75 days",
        "planting_depth": "1-1.5 inches",
        "spacing": "4-6 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "70-85F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Average, well-drained",
        "ph_range": "5.8-7.0",
        "grow_zones": "5-11",
        "spring_planting": "Mar-Jun",
        "fall_planting": "Aug-Sep",
        "sow_months": "Mar-Jun, Aug-Sep",
        "harvest_months": "Jun-Nov",
        "height": "18-24 inches (bush)",
        "spread": "12-18 inches",
        "growing_notes": "Heat-loving southern staple. Thrives in Florida. Full sun. Nitrogen fixer - improves soil. Very drought tolerant once established. Does not need rich soil. Easy to grow. Successive plantings every 2-3 weeks for continuous harvest.",
        "harvest_notes": "Shell peas: harvest when pods are plump and starting to dry. Snap peas: harvest young tender pods. Dry peas: leave on vine until pods are completely dry and brown. Very productive in Florida.",
    },
    43: {  # Blue Butterfly Pea
        "latin_name": "Clitoria ternatea",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "60-90 days to flower",
        "planting_depth": "1/2 inch",
        "spacing": "12-18 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "70-80F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.5",
        "grow_zones": "9-11",
        "spring_planting": "Mar-Jun",
        "sow_months": "Mar-Jun",
        "harvest_months": "Jun-Nov flowers",
        "height": "Vine to 10-15 feet",
        "spread": "Spreading vine",
        "special_requirements": "Scarify or soak seeds 24 hours. Needs trellis or support.",
        "growing_notes": "Beautiful tropical vine with intense blue flowers. Thrives in Florida. Full sun. Nitrogen fixer. Flowers used as natural blue food dye. Self-seeds readily. Can be perennial in Zone 9b. Attracts pollinators.",
        "harvest_notes": "Pick flowers daily when fully open - fresh or dried for tea. Flowers dry to deep blue. Steep in hot water for vivid blue tea that turns purple with lemon juice (pH indicator). Dried flowers store well.",
        "medicinal_notes": "Rich in anthocyanins - potent antioxidant. Traditional Ayurvedic nootropic (brain tonic). Research supports memory and cognitive enhancement. Anti-anxiety properties. Blue tea is caffeine-free. Used as natural food coloring. Generally safe.",
    },
    44: {  # Toothache Plant
        "latin_name": "Acmella oleracea",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "60-75 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "70-80F",
        "light_to_germinate": "Light required",
        "soil_type": "Rich, moist, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "9-11",
        "spring_planting": "Mar-Jun",
        "sow_months": "Mar-Jun",
        "harvest_months": "May-Nov",
        "height": "12-18 inches",
        "spread": "12-18 inches",
        "growing_notes": "Also called Spilanthes or Buzz Buttons. Thrives in Florida heat and humidity. Yellow-red button flowers with distinctive tingling/numbing sensation when eaten. Full sun to part shade. Keep moist. Easy annual.",
        "harvest_notes": "Harvest flower buds (buzz buttons) when yellow with red center. Leaves also have numbing effect. Use fresh for strongest effect. Can be tinctured in alcohol for topical use.",
        "medicinal_notes": "Natural oral analgesic - chew flower bud for toothache, sore gums, canker sores. Contains spilanthol which causes tingling/numbing. Immune stimulant. Antifungal. Used in natural dentistry. Also trendy cocktail ingredient (buzz buttons). Safe in moderate amounts.",
    },
    45: {  # Yellow Everglade Tomato
        "latin_name": "Solanum lycopersicum 'Yellow Everglades'",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "60-70 days",
        "planting_depth": "1/4 inch",
        "spacing": "36-48 inches",
        "row_spacing": "48-60 inches",
        "optimal_germ_temp": "70-80F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Rich, well-drained, fertile",
        "ph_range": "6.0-6.8",
        "grow_zones": "8-11",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Aug-Sep",
        "sow_months": "Feb-Mar, Aug-Sep",
        "harvest_months": "May-Nov",
        "indoor_start": "6-8 weeks before transplanting",
        "height": "Indeterminate vine 6-10 feet",
        "spread": "36-48 inches",
        "growing_notes": "Yellow variant of the Everglades cherry tomato. Same excellent heat tolerance and disease resistance. Vigorous indeterminate vine. Prolific producer. Self-seeds readily. Needs strong support/caging.",
        "harvest_notes": "Pick when golden yellow. Sweet, mild flavor - less acidic than red varieties. Very prolific - harvest daily. Self-seeds aggressively. Great for fresh eating and salads.",
    },
    46: {  # Pigeon Pea
        "latin_name": "Cajanus cajan",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "120-180 days",
        "planting_depth": "1 inch",
        "spacing": "36-48 inches",
        "row_spacing": "48-72 inches",
        "optimal_germ_temp": "70-85F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Average to poor, well-drained",
        "ph_range": "5.0-7.0",
        "grow_zones": "9-11",
        "spring_planting": "Mar-Jun",
        "sow_months": "Mar-Jun",
        "harvest_months": "Oct-Feb",
        "height": "48-96 inches (shrub)",
        "spread": "36-48 inches",
        "growing_notes": "Tropical perennial legume shrub. Excellent for Florida - heat and drought tolerant. Major nitrogen fixer. Can be grown as living fence or windbreak. Fixes 40-200 lbs nitrogen/acre. Host plant for sulphur butterflies. Freezes back but regrows in Zone 9b.",
        "harvest_notes": "Harvest green peas from pods when plump (like shelling peas). Or allow to dry on plant for dried peas (dal). Very productive. Pods can be harvested over several months.",
    },
    47: {  # Caribbean Callaloo
        "latin_name": "Amaranthus viridis",
        "days_to_germination": "7-10 days",
        "days_to_maturity": "40-60 days (greens)",
        "planting_depth": "Surface sow or barely cover",
        "spacing": "6-8 inches",
        "row_spacing": "12-18 inches",
        "optimal_germ_temp": "70-85F",
        "light_to_germinate": "Light required",
        "soil_type": "Rich, moist, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "8-11",
        "spring_planting": "Mar-Aug",
        "sow_months": "Mar-Aug",
        "harvest_months": "May-Nov",
        "height": "24-48 inches",
        "spread": "12-18 inches",
        "growing_notes": "Tropical amaranth greens - Caribbean staple. Thrives in Florida summer heat when lettuce and spinach bolt. Full sun. Succession plant every 2-3 weeks. Self-seeds readily. Very fast growing. Also called bhaji in Indian cooking.",
        "harvest_notes": "Harvest young leaves and tender stems when 6-12 inches tall. Cut and come again - will regrow from base. Or harvest whole plant. Cook like spinach - sauté, soup, stew. Very nutritious.",
    },
    48: {  # Loofah Gourd
        "latin_name": "Luffa aegyptiaca",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "120-150 days",
        "planting_depth": "1 inch",
        "spacing": "36-48 inches",
        "row_spacing": "72-96 inches",
        "optimal_germ_temp": "75-85F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Rich, well-drained, fertile",
        "ph_range": "6.0-6.8",
        "grow_zones": "7-11",
        "spring_planting": "Mar-May",
        "sow_months": "Mar-May",
        "harvest_months": "Young fruit: Jul-Sep, Sponge: Oct-Nov",
        "height": "Vine to 15-30 feet",
        "spread": "Spreading vine",
        "special_requirements": "Needs strong trellis. Long growing season - start indoors in shorter season areas. Soak seeds 24 hours.",
        "growing_notes": "Vigorous tropical vine. Thrives in Florida heat. Needs very sturdy trellis or fence. Full sun. Rich soil. Consistent water during fruiting. Yellow flowers. Dual purpose: young fruit edible, mature fruit is sponge.",
        "harvest_notes": "For eating: harvest when 4-6 inches, before fibers develop. For sponges: leave on vine until skin turns brown and dry. Peel skin, shake out seeds, rinse and dry sponge. Bleach in dilute solution if desired.",
    },
    49: {  # Purple Passion Flower
        "latin_name": "Passiflora incarnata",
        "days_to_germination": "30-90 days (slow and erratic)",
        "days_to_maturity": "Second year fruiting",
        "planting_depth": "1/4 inch",
        "spacing": "36-60 inches",
        "row_spacing": "72 inches",
        "optimal_germ_temp": "70-80F",
        "light_to_germinate": "Light helpful",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.5",
        "grow_zones": "5-9",
        "spring_planting": "Feb-Apr",
        "sow_months": "Feb-Apr",
        "harvest_months": "Jul-Oct fruit",
        "height": "Vine to 15-25 feet",
        "spread": "Spreading vine",
        "special_requirements": "Scarify seeds. Cold stratification 8-12 weeks greatly improves germination. Very slow, erratic germination - be patient.",
        "growing_notes": "Native Florida vine. Spectacular purple and white flowers. Host plant for Gulf Fritillary butterflies. Spreads by root suckers - can be aggressive. Full sun to part shade. Drought tolerant once established. Dies back in winter, returns vigorously in spring.",
        "harvest_notes": "Fruits (maypops) ripen when they fall from vine or turn yellow-wrinkled. Pulp is aromatic and edible fresh. Leaves and flowers harvested for tea. Best harvested during flowering.",
        "medicinal_notes": "Premier calming nervine. Excellent for anxiety, insomnia, nervous restlessness. Non-habit-forming sleep aid. Antispasmodic for muscle tension. Combines well with valerian and skullcap. Leaf and flower tea or tincture. Safe for most adults. CAUTION: May potentiate sedative medications.",
    },
    50: {  # Feverfew
        "latin_name": "Tanacetum parthenium",
        "days_to_germination": "10-14 days",
        "days_to_maturity": "90-120 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "65-70F",
        "light_to_germinate": "Light required",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "5-10",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Mar, Sep-Oct",
        "harvest_months": "Apr-Oct",
        "height": "12-24 inches",
        "spread": "12-18 inches",
        "growing_notes": "Attractive daisy-like flowers. Easy to grow. Self-seeds readily. Full sun to light shade. Tolerates poor soil. Short-lived perennial. Deer resistant. Strong chrysanthemum-like scent.",
        "harvest_notes": "Harvest leaves before flowering for highest medicinal potency. Use fresh or dried. Flowers also used. Freeze fresh leaves for convenience.",
        "medicinal_notes": "Best known for migraine prevention (NOT acute treatment). Must be taken daily as preventive. Also anti-inflammatory for arthritis. Chew 1-2 fresh leaves daily or take capsules. CAUTION: Can cause mouth ulcers from fresh leaf. Avoid during pregnancy. May interact with blood thinners. Daisy family allergy possible.",
    },
    51: {  # Red Raspberry
        "latin_name": "Rubus idaeus",
        "days_to_germination": "30-60 days (stratification needed)",
        "days_to_maturity": "Second year fruiting from seed",
        "planting_depth": "1/4 inch",
        "spacing": "24-36 inches",
        "row_spacing": "72-96 inches",
        "optimal_germ_temp": "60-70F after stratification",
        "light_to_germinate": "Light helpful",
        "soil_type": "Rich, slightly acidic, well-drained",
        "ph_range": "5.5-6.5",
        "grow_zones": "3-8",
        "spring_planting": "Jan-Feb (after stratification)",
        "sow_months": "Jan-Feb",
        "harvest_months": "May-Jul berries",
        "height": "36-72 inches",
        "spread": "24-36 inches (spreading)",
        "special_requirements": "Cold stratification 60-90 days required. Challenging in Zone 9b - may not get enough chill hours. Consider Mysore raspberry for Florida.",
        "growing_notes": "Challenging in Florida due to heat and humidity. Needs cold dormancy period. Partial shade essential. Very well-drained acidic soil. Consider tropical/subtropical raspberry varieties (Mysore, Nantahala) better suited to Zone 9b. Mulch heavily.",
        "harvest_notes": "Berries ripen over several weeks. Pick when easily detaching from plant. Very perishable - use or freeze immediately. Summer-bearing types fruit on second-year canes.",
        "medicinal_notes": "Leaf tea is premier women's health herb. Tones uterine muscles - used in late pregnancy to prepare for labor. Rich in iron, calcium, magnesium. Nutrient-dense tea for menstrual support. Astringent for diarrhea. Very safe as food and tea.",
    },
    52: {  # Lemon Balm
        "latin_name": "Melissa officinalis",
        "days_to_germination": "10-14 days",
        "days_to_maturity": "70-80 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "18-24 inches",
        "row_spacing": "24 inches",
        "optimal_germ_temp": "65-70F",
        "light_to_germinate": "Light required",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.5",
        "grow_zones": "4-9",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Nov",
        "sow_months": "Feb-Mar, Sep-Nov",
        "harvest_months": "Year-round in Zone 9b",
        "height": "12-24 inches",
        "spread": "18-24 inches (spreading)",
        "special_requirements": "Can spread aggressively by self-seeding. Deadhead to prevent.",
        "growing_notes": "Lemon-scented mint family herb. Very easy to grow - almost too easy. Self-seeds prolifically. Partial shade in Florida. Tolerates poor soil. Can become invasive. Attracts bees. Dies back in hottest months but returns.",
        "harvest_notes": "Harvest leaves before flowering for best flavor. Cut stems above lowest leaves for regrowth. Best used fresh - much of the lemon aroma is lost in drying. Freeze in ice cubes for preservation.",
        "medicinal_notes": "Calming and antiviral. Excellent for anxiety, insomnia, nervous digestive upset. Topical for cold sores/herpes (antiviral against HSV). Thyroid-calming (avoid with hypothyroid). Safe and pleasant-tasting tea for children. Combines well with chamomile for sleep.",
    },
    53: {  # Stevia
        "latin_name": "Stevia rebaudiana",
        "days_to_germination": "14-21 days (low germination rate)",
        "days_to_maturity": "90-120 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "68-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Rich, moist, well-drained loam",
        "ph_range": "6.0-7.0",
        "grow_zones": "8-11",
        "spring_planting": "Mar-May",
        "sow_months": "Mar-May",
        "harvest_months": "Jun-Nov",
        "height": "12-24 inches",
        "spread": "12-18 inches",
        "special_requirements": "Low seed germination rate (10-20%). Start many seeds. Fresh seed germinates best.",
        "growing_notes": "Natural sweetener plant - leaves are 30-40x sweeter than sugar. Full sun to light shade. Keep consistently moist. Perennial in Zone 9b. Pinch tips to promote bushy growth. May die back in winter but returns from roots.",
        "harvest_notes": "Harvest leaves before flowering (sweetness decreases after). Cut stems leaving 4 inches for regrowth. Dry leaves and crush to powder for sweetening. Fresh leaves in tea. Major harvest before first frost.",
    },
    54: {  # Fenugreek
        "latin_name": "Trigonella foenum-graecum",
        "days_to_germination": "3-5 days",
        "days_to_maturity": "60-90 days (seed), 21-30 (microgreens)",
        "planting_depth": "1/4-1/2 inch",
        "spacing": "4-6 inches",
        "row_spacing": "12-18 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "4-11",
        "spring_planting": "Feb-Apr, Sep-Nov (cool season in FL)",
        "fall_planting": "Sep-Nov",
        "sow_months": "Sep-Apr",
        "harvest_months": "Greens: 3-4 weeks; Seeds: 3-4 months",
        "height": "12-24 inches",
        "spread": "6-8 inches",
        "growing_notes": "Cool season annual in Florida. Fast-germinating. Nitrogen fixer. Grow for microgreens/sprouts, fresh greens (methi), or dried seeds. Full sun. Sow thickly for greens. Easy and fast.",
        "harvest_notes": "Sprouts: 3-5 days. Microgreens: 7-14 days. Fresh greens (methi): cut at 4-6 inches. Seeds: harvest when pods turn yellow-brown. Dry pods and thresh seeds.",
        "medicinal_notes": "Galactagogue - increases breast milk production. Regulates blood sugar - studied for diabetes. Lowers cholesterol. Soaked seeds for digestive mucilage. Rich in iron. Seeds taste like maple syrup. CAUTION: Can cause maple syrup odor in sweat/urine. Avoid during pregnancy (uterine stimulant).",
    },
    55: {  # Butterfly Weed
        "latin_name": "Asclepias tuberosa",
        "days_to_germination": "21-30 days",
        "days_to_maturity": "Second year flowering",
        "planting_depth": "1/4 inch",
        "spacing": "18-24 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Sandy, well-drained, lean",
        "ph_range": "5.5-7.0",
        "grow_zones": "3-9",
        "spring_planting": "Feb-Mar (after stratification)",
        "sow_months": "Feb-Mar",
        "height": "18-36 inches",
        "spread": "12-18 inches",
        "special_requirements": "Cold stratification 4-6 weeks. Taproot - does not transplant well. Direct sow or use peat pots.",
        "growing_notes": "Native milkweed with brilliant orange flowers. CRITICAL monarch butterfly host plant. Unlike other milkweeds, prefers dry well-drained soil. Deep taproot - very drought tolerant. Full sun. Slow to establish but long-lived. Does not spread by runners.",
        "harvest_notes": "Do not harvest - this is a conservation plant for monarch butterflies. Allow seed pods to mature and release seeds naturally. Collect seeds from dried pods in fall if desired for propagation.",
    },
    56: {  # Puerto Rican Black Cowpea
        "latin_name": "Vigna unguiculata 'Puerto Rican Black'",
        "days_to_germination": "7-10 days",
        "days_to_maturity": "60-75 days",
        "planting_depth": "1-1.5 inches",
        "spacing": "4-6 inches",
        "row_spacing": "24-36 inches",
        "optimal_germ_temp": "70-85F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Average, well-drained",
        "ph_range": "5.8-7.0",
        "grow_zones": "5-11",
        "spring_planting": "Mar-Jun",
        "fall_planting": "Aug-Sep",
        "sow_months": "Mar-Jun, Aug-Sep",
        "harvest_months": "Jun-Nov",
        "height": "18-24 inches (bush)",
        "spread": "12-18 inches",
        "growing_notes": "Caribbean cowpea variety with small black seeds. Excellent in Florida heat. Full sun. Nitrogen fixer. Drought tolerant. Very productive. Traditional Puerto Rican variety. Bush type - no trellis needed.",
        "harvest_notes": "Harvest snap beans when young and tender. For dry beans, leave pods on plant until fully dry and brown. Shell dry beans and store. Very productive in warm weather.",
    },
    57: {  # Florida Market Eggplant
        "latin_name": "Solanum melongena 'Florida Market'",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "80-90 days",
        "planting_depth": "1/4 inch",
        "spacing": "24-30 inches",
        "row_spacing": "30-36 inches",
        "optimal_germ_temp": "75-85F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Rich, well-drained, fertile",
        "ph_range": "5.5-6.5",
        "grow_zones": "5-11",
        "spring_planting": "Feb-Apr",
        "fall_planting": "Aug-Sep",
        "sow_months": "Feb-Apr, Aug-Sep",
        "harvest_months": "May-Nov",
        "indoor_start": "8-10 weeks before transplanting",
        "height": "24-36 inches",
        "spread": "24-30 inches",
        "growing_notes": "Florida-adapted variety bred for heat tolerance. Full sun. Rich soil with consistent moisture. Mulch heavily. Stake or cage plants. Watch for flea beetles. Very productive in Florida.",
        "harvest_notes": "Harvest when skin is glossy and firm - press thumb in, if indentation springs back it's ready. Overripe fruit has dull skin and brown seeds. Use sharp knife or pruners to cut from plant.",
    },
    58: {  # Florida Broadleaf Mustard
        "latin_name": "Brassica juncea 'Florida Broadleaf'",
        "days_to_germination": "4-7 days",
        "days_to_maturity": "40-50 days",
        "planting_depth": "1/4 inch",
        "spacing": "6-12 inches",
        "row_spacing": "12-18 inches",
        "optimal_germ_temp": "60-70F",
        "light_to_germinate": "Light or dark",
        "soil_type": "Rich, moist, well-drained",
        "ph_range": "6.0-7.0",
        "grow_zones": "3-11",
        "spring_planting": "Oct-Feb (cool season in FL)",
        "fall_planting": "Oct-Nov",
        "sow_months": "Oct-Feb",
        "harvest_months": "Nov-Apr",
        "height": "18-24 inches",
        "spread": "12-18 inches",
        "growing_notes": "Cool season green in Florida. Very fast growing. Direct sow in fall. Bolts quickly in warm weather. Large, crinkled leaves with spicy flavor. Succession plant every 2 weeks. Full sun to light shade.",
        "harvest_notes": "Harvest outer leaves when young for mildest flavor. Or cut whole plant at base. Baby leaves for salads, larger leaves for cooking (braising, stir-fry, soups). Peppery, spicy flavor mellows with cooking.",
    },
    59: {  # Pápalo Herb
        "latin_name": "Porophyllum ruderale",
        "days_to_germination": "7-14 days",
        "days_to_maturity": "50-70 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "70-80F",
        "light_to_germinate": "Light required",
        "soil_type": "Average, well-drained",
        "ph_range": "6.0-7.5",
        "grow_zones": "8-11",
        "spring_planting": "Mar-Jun",
        "sow_months": "Mar-Jun",
        "harvest_months": "May-Nov",
        "height": "24-48 inches",
        "spread": "18-24 inches",
        "growing_notes": "Mexican herb used as cilantro substitute in summer when cilantro bolts. Thrives in extreme heat. Full sun. Very easy to grow. Strong flavor - use sparingly. Self-seeds. Annual in most areas.",
        "harvest_notes": "Harvest young leaves for best flavor. Strong, pungent taste - a little goes a long way. Used fresh in tacos, salsas, beans. Flavor does not preserve well - use fresh only.",
    },
    60: {  # Beautyberry
        "latin_name": "Callicarpa americana",
        "days_to_germination": "30-90 days",
        "days_to_maturity": "2-3 years to fruiting",
        "planting_depth": "1/4 inch",
        "spacing": "48-72 inches",
        "row_spacing": "72-96 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light helpful",
        "soil_type": "Average, moist, adaptable",
        "ph_range": "5.5-7.0",
        "grow_zones": "6-10",
        "spring_planting": "Feb-Mar (after stratification)",
        "sow_months": "Feb-Mar",
        "harvest_months": "Sep-Nov berries",
        "height": "48-96 inches",
        "spread": "48-96 inches",
        "special_requirements": "Cold stratification 90 days. Slow germination. Easier from cuttings or nursery plants.",
        "growing_notes": "Native Florida shrub with stunning iridescent purple berries in fall. Understory plant - partial shade to full sun. Very adaptable. Wildlife food source. Low maintenance once established. Can be hard-pruned in late winter for compact shape.",
        "harvest_notes": "Berries ripen in fall when brilliantly purple. Make jelly (beautyberry jelly is a Southern tradition). Leaves crushed as natural insect repellent. Berries not palatable raw but excellent in jelly.",
    },
    61: {  # Deer Berry
        "latin_name": "Vaccinium stamineum",
        "days_to_germination": "30-90 days",
        "days_to_maturity": "3-5 years to fruiting",
        "planting_depth": "Surface sow on acidic medium",
        "spacing": "48-72 inches",
        "row_spacing": "72-96 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Acidic, sandy, well-drained",
        "ph_range": "4.5-5.5",
        "grow_zones": "5-9",
        "spring_planting": "Feb-Mar (after stratification)",
        "sow_months": "Feb-Mar",
        "harvest_months": "Jul-Sep berries",
        "height": "36-72 inches",
        "spread": "36-60 inches",
        "special_requirements": "Cold stratification 90 days. Needs acidic soil. Difficult from seed - cuttings or nursery plants easier.",
        "growing_notes": "Native Florida Vaccinium. Partial shade to full sun. Must have acidic soil - amend with pine bark and sulfur. Drought tolerant once established. Deciduous. Attractive bell-shaped flowers. Important wildlife food.",
        "harvest_notes": "Berries ripen midsummer. Tart flavor - best in jams, jellies, pies. Named because deer love the berries. Can be eaten fresh when fully ripe though flavor is tart.",
    },
    62: {  # Sand Blackberry
        "latin_name": "Rubus cuneifolius",
        "days_to_germination": "30-90 days",
        "days_to_maturity": "Second year fruiting",
        "planting_depth": "1/4 inch",
        "spacing": "36-48 inches",
        "row_spacing": "72-96 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light helpful",
        "soil_type": "Sandy, acidic, well-drained",
        "ph_range": "4.5-6.0",
        "grow_zones": "5-9",
        "spring_planting": "Feb-Mar (after stratification)",
        "sow_months": "Feb-Mar",
        "harvest_months": "May-Jun berries",
        "height": "36-48 inches",
        "spread": "36-48 inches (spreading)",
        "special_requirements": "Cold stratification 90 days. Spreads by suckers. Thorny canes.",
        "growing_notes": "Native Florida blackberry adapted to sandy soils. Full sun to part shade. Drought tolerant. Spreads by root suckers - can be contained with barriers. Thorny - plant away from paths. Good erosion control plant. Tough and low maintenance.",
        "harvest_notes": "Berries ripen late spring to early summer. Pick when completely black and easily detaching. Very perishable - eat or freeze immediately. Excellent flavor. Fruits on second-year canes.",
    },
    63: {  # Serviceberry
        "latin_name": "Amelanchier arborea",
        "days_to_germination": "30-90 days",
        "days_to_maturity": "3-5 years to fruiting",
        "planting_depth": "1/4 inch",
        "spacing": "72-120 inches",
        "row_spacing": "120-180 inches",
        "optimal_germ_temp": "60-70F after stratification",
        "light_to_germinate": "Light helpful",
        "soil_type": "Moist, acidic, well-drained",
        "ph_range": "5.0-6.5",
        "grow_zones": "4-9",
        "spring_planting": "Feb-Mar (after stratification)",
        "sow_months": "Feb-Mar",
        "harvest_months": "Apr-May berries",
        "height": "120-300 inches (tree)",
        "spread": "96-180 inches",
        "special_requirements": "Cold stratification 90-120 days required. Slow to establish from seed.",
        "growing_notes": "Native understory tree. Beautiful white spring flowers followed by edible berries. Partial shade to full sun. Moist acidic soil. Attractive multi-season interest - flowers, berries, fall color. Low maintenance once established.",
        "harvest_notes": "Berries ripen in spring (early for a fruit tree). Sweet, blueberry-like flavor. Birds compete for berries - may need netting. Use fresh, in pies, jams. Also called Juneberry or Saskatoon berry.",
    },
    64: {  # Shiny Blueberry
        "latin_name": "Vaccinium myrsinites",
        "days_to_germination": "30-90 days",
        "days_to_maturity": "3-5 years to fruiting",
        "planting_depth": "Surface sow on acidic medium",
        "spacing": "36-48 inches",
        "row_spacing": "48-72 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Acidic, sandy, moist to dry",
        "ph_range": "4.0-5.5",
        "grow_zones": "7-10",
        "spring_planting": "Feb-Mar",
        "sow_months": "Feb-Mar",
        "harvest_months": "Apr-Jun berries",
        "height": "12-24 inches",
        "spread": "24-36 inches (spreading)",
        "special_requirements": "Needs very acidic soil. Mycorrhizal fungi beneficial. Cold stratification helps.",
        "growing_notes": "Native Florida evergreen blueberry. Low-growing shrub perfect for groundcover. Extremely well-adapted to Florida's sandy acidic soils. Drought tolerant. Full sun to partial shade. Spreads slowly by suckers. Evergreen in Zone 9b.",
        "harvest_notes": "Small but flavorful berries in spring. Sweeter than many cultivated varieties. Harvest when dark blue. Birds will compete - netting helps. Use fresh or in preserves.",
    },
    65: {  # Sparkleberry
        "latin_name": "Vaccinium arboreum",
        "days_to_germination": "30-90 days",
        "days_to_maturity": "5+ years to significant fruiting",
        "planting_depth": "Surface sow on acidic medium",
        "spacing": "72-120 inches",
        "row_spacing": "120 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Acidic, sandy, well-drained",
        "ph_range": "4.5-5.5",
        "grow_zones": "7-9",
        "spring_planting": "Feb-Mar (after stratification)",
        "sow_months": "Feb-Mar",
        "harvest_months": "Sep-Nov berries",
        "height": "120-240 inches (tree form)",
        "spread": "72-120 inches",
        "special_requirements": "Very slow growing. Cold stratification 90 days. Difficult from seed.",
        "growing_notes": "Native Florida tree-form blueberry. Beautiful bark and fall color. Drought tolerant. Used as rootstock for cultivated blueberries. Full sun to partial shade. Sandy acidic soil. Long-lived and very ornamental. Important wildlife tree.",
        "harvest_notes": "Small dark berries ripen in fall (later than other blueberries). Flavor is good but berries are small and have larger seeds than cultivated types. Used for jams and wildlife planting.",
    },
    66: {  # Florida Calamint
        "latin_name": "Clinopodium ashei",
        "days_to_germination": "14-30 days",
        "days_to_maturity": "First year flowering",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Sandy, well-drained, lean",
        "ph_range": "5.5-7.0",
        "grow_zones": "8-10",
        "spring_planting": "Feb-Apr",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Apr, Sep-Oct",
        "harvest_months": "Year-round leaves",
        "height": "12-18 inches",
        "spread": "12-18 inches",
        "growing_notes": "Florida endemic mint-family plant. Excellent pollinator magnet - bees love it. Full sun. Sandy well-drained soil. Very drought tolerant. Low maintenance. Aromatic minty foliage. Endangered in wild - growing it helps conservation.",
        "harvest_notes": "Harvest sprigs for tea anytime. Pleasant minty flavor. Light harvest to avoid stressing the plant. Primarily grown as ornamental pollinator plant.",
    },
    67: {  # Florida Mountain Mint
        "latin_name": "Pycnanthemum floridanum",
        "days_to_germination": "14-30 days",
        "days_to_maturity": "First year flowering",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "18-24 inches",
        "row_spacing": "24 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Sandy to average, well-drained",
        "ph_range": "5.5-7.0",
        "grow_zones": "8-10",
        "spring_planting": "Feb-Apr",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Apr, Sep-Oct",
        "harvest_months": "Year-round",
        "height": "18-36 inches",
        "spread": "18-24 inches (spreading)",
        "growing_notes": "Outstanding native pollinator plant - one of the best bee plants in Florida. White flower clusters. Strong minty aroma. Full sun to light shade. Drought tolerant. Spreads by rhizomes. Easy to grow once established.",
        "harvest_notes": "Harvest leaves and flowers for tea. Strong minty flavor. Dry for winter tea. Can be harvested throughout growing season. Silvery-white bracts are attractive in dried arrangements.",
    },
    68: {  # Lyreleaf Sage
        "latin_name": "Salvia lyrata",
        "days_to_germination": "14-21 days",
        "days_to_maturity": "First year flowering",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Average, adaptable",
        "ph_range": "5.5-7.0",
        "grow_zones": "5-10",
        "spring_planting": "Feb-Mar",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Mar, Sep-Oct",
        "height": "12-24 inches",
        "spread": "12-18 inches",
        "growing_notes": "Native Florida sage. Basal rosette of lyre-shaped leaves with lavender-blue flower spikes. Full sun to partial shade. Adaptable to various soils. Self-seeds. Good lawn alternative - tolerates mowing. Pollinator friendly.",
        "harvest_notes": "Primarily ornamental and pollinator plant. Leaves and flowers can be used in tea. Self-seeds freely for naturalized plantings.",
    },
    69: {  # Florida Horse Mint
        "latin_name": "Monarda punctata",
        "days_to_germination": "10-21 days",
        "days_to_maturity": "90-120 days",
        "planting_depth": "Surface sow, press lightly",
        "spacing": "12-18 inches",
        "row_spacing": "18-24 inches",
        "optimal_germ_temp": "65-75F",
        "light_to_germinate": "Light required",
        "soil_type": "Sandy, well-drained, lean",
        "ph_range": "5.5-7.0",
        "grow_zones": "4-10",
        "spring_planting": "Feb-Apr",
        "fall_planting": "Sep-Oct",
        "sow_months": "Feb-Apr, Sep-Oct",
        "harvest_months": "May-Sep",
        "height": "24-36 inches",
        "spread": "12-18 inches",
        "growing_notes": "Native Monarda with spotted flowers and showy pink/lavender bracts. Outstanding pollinator plant. Full sun. Sandy well-drained soil. Very drought tolerant. Self-seeds. Contains thymol - aromatic leaves.",
        "harvest_notes": "Harvest flowering tops for tea and medicinal use. High in thymol - antiseptic properties. Dry for winter use. Beautiful in dried arrangements.",
        "medicinal_notes": "High thymol content - natural antiseptic and antimicrobial. Tea for respiratory infections, digestive upset. Traditional Native American remedy. Used similarly to thyme medicinally. Contains carvacrol as well.",
    },
    70: {  # Common Pumpkin
        "latin_name": "Cucurbita pepo",
        "days_to_germination": "5-10 days",
        "days_to_maturity": "90-120 days",
        "planting_depth": "1 inch",
        "spacing": "48-72 inches",
        "row_spacing": "72-120 inches",
        "optimal_germ_temp": "70-85F",
        "light_to_germinate": "Darkness preferred",
        "soil_type": "Rich, well-drained, fertile",
        "ph_range": "6.0-6.8",
        "grow_zones": "3-9",
        "spring_planting": "Mar-Apr",
        "sow_months": "Mar-Apr",
        "harvest_months": "Jul-Oct",
        "height": "Vine to 10-20 feet",
        "spread": "Spreading vine 10-20 feet",
        "growing_notes": "Needs lots of space. Full sun. Rich soil with compost. Consistent water during fruiting. Watch for squash vine borers and powdery mildew in Florida. Seminole Pumpkin may be better adapted for Florida. Plant on mounds for drainage.",
        "harvest_notes": "Harvest when skin is hard and deep orange. Stem should be dry and corky. Cut from vine leaving 4-inch stem. Cure in sun for a week. Stores 2-3 months in cool dry place. Seeds edible roasted.",
    },
}


def main():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    updated = 0
    skipped = 0

    for seed_id, data in SEED_DATA.items():
        # Build SET clause only for non-None fields
        fields = []
        values = []
        for key, val in data.items():
            if val is not None:
                fields.append(f"{key} = ?")
                values.append(val)

        if not fields:
            skipped += 1
            continue

        values.append(seed_id)
        sql = f"UPDATE seeds SET {', '.join(fields)} WHERE id = ?"

        try:
            cursor.execute(sql, values)
            if cursor.rowcount > 0:
                updated += 1
                print(f"  Updated #{seed_id}: {data.get('latin_name', 'unknown')}")
            else:
                print(f"  SKIP #{seed_id}: not found in database")
                skipped += 1
        except Exception as e:
            print(f"  ERROR #{seed_id}: {e}")
            skipped += 1

    conn.commit()
    conn.close()
    print(f"\nDone: {updated} updated, {skipped} skipped")


if __name__ == "__main__":
    main()
